Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2022-10, with the labels that each got.

#290 7.1.4 Untertitel-Anpassungen: Unbedeutende sprachliche Änderung
  Prüfschritte/de/7.1.4 Untertitel-Anpassungen.adoc
Labels: changelog:changed :pencil2:, version:patch

#288 5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung: Anwendbarkeit bei Konvertierung von HTML-Ziel- und Quellformat entfernt
  Prüfschritte/de/5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung.adoc
Labels: changelog:changed :pencil2:, version:minor

#294 7.1.5 Gesprochene Untertitel: Hinzufügung einer ITU-Quelle mit Umsetzungsempfehlungen
  Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
Labels: changelog:added :heavy_plus_sign:, version:patch

#217 9.4.1.2 Name, Rolle, Wert verfügbar: Konsole-Script für die semantische Untersuchung von dynamisch eingeblendeten Inhalten mit den Entwicklerwerkzeugen
  Prüfschritte/de/9.4.1.2 Name-Rolle-Wert verfügbar.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor
