Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2022-09, with the labels that each got.

#262 9.1.4.3 Kontraste von Texten ausreichend: Konkretisierung hinsichtlich Styleswitcher-Element
  Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc
Labels: changelog:added :heavy_plus_sign:, version:patch

#251 9.3.3.3 Hilfe bei Fehlern: Ausnahme bei Sicherheitsrisiko.adoc
  Prüfschritte/de/9.3.3.3 Hilfe bei Fehlern.adoc
Labels: changelog:added :heavy_plus_sign:, version:patch

#242 9.2.4.4 Aussagekräftige Linktexte: Frage zu Mehrfachverlinkungen entfernt
  Prüfschritte/de/9.2.4.4 Aussagekräftige Linktexte.adoc
Labels: changelog:changed :pencil2:, version:patch

#236 7.3 Bedienelemente für Untertitel und Audiodeskription: Anwendbar, nur wenn UT / AD angeboten werden
  Prüfschritte/de/7.3 Bedienelemente für Untertitel und Audiodeskription.adoc
Labels: changelog:changed :pencil2:, version:patch

#235 7.1.1 Wiedergabe von Untertiteln: Konkretisierung - Anwendbar, wenn Untertitel vorhanden sind (statt zuschaltbar)
  Prüfschritte/de/7.1.1 Wiedergabe von Untertiteln.adoc
Labels: changelog:changed :pencil2:, version:patch

#278 11.8.4 Reparaturassistenz: Korrektur der Überschriftenstruktur der Prüfschrittbeschreibung
  Prüfschritte/de/11.8.4 Reparaturassistenz.adoc
Labels: changelog:fixed :+1:, version:patch

#277 9.3.3.1 Fehlererkennung: Zusätzlicher Hinweis hinsichtlich unzureichender Unterstützung von aria-errormessage
  Prüfschritte/de/9.3.3.1 Fehlererkennung.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#231 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit: Anwendbarkeit und Prüfung konkretisiert, Ausnahme hinzugefügt
  Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#280 Update 12.1.2 Barrierefreie Dokumentation.adoc
  Prüfschritte/de/12.1.2 Barrierefreie Dokumentation.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#282 5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung: Eingrenzung auf HTML-HTML-Konvertierung
  Prüfschritte/de/5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung.adoc
Labels: changelog:changed :pencil2:, version:minor

#283 9.2.2.1 Zeitbegrenzungen anpassbar: Anwendbar, wenn Zeitbegrenzung gegeben (nicht nur bei Seiten mit Transaktion)
  Prüfschritte/de/9.2.2.1 Zeitbegrenzungen anpassbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#285 9.2.4.2 Sinnvolle Dokumenttitel - Tippfehler-Korrektur
  Prüfschritte/de/9.2.4.2 Sinnvolle Dokumenttitel.adoc
Labels: changelog:fixed :+1:, version:patch
