Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2023-09, with the labels that each got.

#370 9.1.3.2 Sinnvolle Reihenfolge: Prüfung geändert
  Prüfschritte/de/9.1.3.2 Sinnvolle Reihenfolge.adoc
Labels: changelog:changed :pencil2:, version:minor

#346 9.2.4.7 Aktuelle Position des Fokus deutlich - Bezug zu 9.1.4.11
  Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#338 9.1.3.1e Datentabellen richtig aufgebaut: Quelle hinzugefügt
  Prüfschritte/de/9.1.3.1e Datentabellen richtig aufgebaut.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#372 11.7 Benutzerdefinierte Einstellungen: Korrektur von Rechtschreibfehlern
  Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc
Labels: changelog:changed :pencil2:, version:patch

#353 9.3.2.1 Keine unerwartete Kontextänderung bei Fokus: Verlinkung korrigiert
  Prüfschritte/de/9.3.2.1 Keine unerwartete Kontextänderung bei Fokus.adoc
Labels: changelog:changed :pencil2:, version:patch

#352 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen: Verlinkung korrigiert
  Prüfschritte/de/9.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc
Labels: changelog:changed :pencil2:, version:patch

#351 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Verlinkungen korrigiert
  Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Labels: changelog:changed :pencil2:, version:patch

#350 9.1.4.5 Verzicht auf Schriftgrafiken: Verlinkungen korrigiert
  Prüfschritte/de/9.1.4.5 Verzicht auf Schriftgrafiken.adoc
Labels: changelog:changed :pencil2:, version:patch

#349 9.1.4.3 Kontraste von Texten ausreichend: Verlinkung korrigiert
  Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc
Labels: changelog:changed :pencil2:, version:patch

#335 6.2.1.1 Textkommunikation in Echtzeit: neue Quelle ETSI TR
  Prüfschritte/de/6.2.1.1 Textkommunikation in Echtzeit.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#334 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Quelle
  Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#333 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen: unsichtbare…
  Prüfschritte/de/9.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc
Labels: changelog:changed :pencil2:, version:minor

#322 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen: Ergänzung
  Prüfschritte/de/9.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#315 9.2.2.2 Bewegte Inhalte: Ergänzung Bewertung
  Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor
