Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2023-03, with the labels that each got.

#301 9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung: Korrektur: fehlendes Leerzeichen (ggftrotz)
  Prüfschritte/de/9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc
Labels: changelog:fixed :+1:, version:patch

#303 9.3.3.2 Beschriftungen von Formularelementen vorhanden: Ausnahme visuell verständlicher Submit-Button für einfach Suchformulare konkretisiert
  Prüfschritte/de/9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc
Labels: changelog:changed :pencil2:, version:minor

#330 9.1.2.5 Audiodeskription für Videos: Ergänzung Frage
  Prüfschritte/de/9.1.2.5 Audiodeskription für Videos.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#329 9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos: Ergänz…
  Prüfschritte/de/9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc
  Prüfschritte/de/9.1.2.5 Audiodeskription für Videos.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#332 9.3.3.2 Beschriftungen von Formularelementen vorhanden: Kennzeichnung von Pflichtfeldern über Ausweisen optionaler Felder
  Prüfschritte/de/9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc
Labels: changelog:changed :pencil2:, version:minor

#331 9.1.4.1 Ohne Farben nutzbar: Verallgemeinerung
  Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#328 11.7 Benutzerdefinierte Einstellungen: Konkretisierung der Prüfanleitung und Bewertung
  Prüfschritte/de/11.7 Benutzerdefinierte Einstellungen.adoc
Labels: changelog:added :heavy_plus_sign:, changelog:changed :pencil2:

#326 9.1.4.12 Textabstände anpassbar - Ausnahmen, Bewertung
  Prüfschritte/de/9.1.4.12 Textabstände anpassbar.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#293 9.2.1.1 Ohne Maus nutzbar: Ergänzung und kleine Korrekturen bei Anmerkungen
  Prüfschritte/de/9.2.1.1 Ohne Maus nutzbar.adoc
Labels: changelog:added :heavy_plus_sign:, changelog:changed :pencil2:, version:patch
