Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2023-02, with the labels that each got.

#313 9.3.2.1 Keine unerwartete Kontextänderung bei Fokus: Nicht anwendbar als Bewertungsoption ergänzt
  Prüfschritte/de/9.3.2.1 Keine unerwartete Kontextänderung bei Fokus.adoc
Labels: changelog:changed :pencil2:, version:minor

#311 9.2.1.1 Ohne Maus nutzbar: Nicht anwendbar als Bewertungsoption ergänzt
  Prüfschritte/de/9.2.1.1 Ohne Maus nutzbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#310 9.1.4.5 Verzicht auf Schriftgrafiken: Nicht anwendbar als Bewertungsoption ergänzt
  Prüfschritte/de/9.1.4.5 Verzicht auf Schriftgrafiken.adoc
Labels: changelog:changed :pencil2:, version:minor

#312 9.2.2.2 Bewegte Inhalte abschaltbar: Kleinere redaktionelle Optimierung
  Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc
Labels: changelog:fixed :+1:, version:patch

#314 9.2.2.2 Bewegte Inhalte abschaltbar: Prüfung
  Prüfschritte/de/9.2.2.2 Bewegte Inhalte abschaltbar.adoc
Labels: changelog:changed :pencil2:, version:major

#316 9.2.1.4 Tastatur-Kurzbefehle abschaltbar oder anpassbar: Videos
  Prüfschritte/de/9.2.1.4 Tastatur-Kurzbefehle abschaltbar oder anpassbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#318 6.2.1.1 Textkommunikation in Echtzeit: Ergänzung Quelle
  Prüfschritte/de/6.2.1.1 Textkommunikation in Echtzeit.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#321 9.1.4.3 Kontraste von Texten ausreichend: Native Elemente
  Prüfschritte/de/9.1.4.3 Kontraste von Texten ausreichend.adoc
Labels: changelog:added :heavy_plus_sign:, version:major
