Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2024-02, with the labels that each got.

#399 Verschiedene Prüfschritte: Rechtschreibung
  Prüfschritte/de/5.2 Aktivierung von Barrierefreiheitsfunktionen.adoc
Labels: changelog:fixed :+1:, version:patch

#414 Update 9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc
  Prüfschritte/de/9.2.5.1 Alternativen für komplexe Zeiger-Gesten.adoc
Labels: changelog:added :heavy_plus_sign:, version:major

#412 12.1.1 Dokumentation von Kompatibilität u. Barrierefreiheit - Ergänzung Bewertung
  Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#411 9.2.5.8 Zielgröße (Minimum) - Ergänzungen
  Prüfschritte/de/9.2.5.8 Zielgröße (Minimum).adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#410 9.3.2.6 Konsistente Hilfe - Aufklappelement
  Prüfschritte/de/9.3.2.6 Konsistente Hilfe.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#409 9.1.4.11 Kontraste von Grafiken u. grafischen Bedienelementen…Styleswitcher-Prüfung
  Prüfschritte/de/9.1.4.11 Kontraste von Grafiken und grafischen Bedienelementen ausreichend.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#408 9.3.3.8 Zugängliche Authentifizierung (Minimum) - Ergänzungen
  Prüfschritte/de/9.3.3.8 Zugängliche Authentifizierung (Minimum).adoc
Labels: changelog:changed :pencil2:, version:minor

#407 9.2.5.7 Ziehbewegungen: Anwendbarkeit
  Prüfschritte/de/9.2.5.7 Ziehbewegungen.adoc
Labels: changelog:changed :pencil2:, version:patch

#394 9.1.3.1d Inhalt gegliedert - Anpassung bei Absatzauszeichnung und CSS generated content
  Prüfschritte/de/9.1.3.1d Inhalt gegliedert.adoc
Labels: changelog:changed :pencil2:, version:major

#418 9.1.4.5 Verzicht auf Schriftgrafiken - Änderung des Prüfschritt-Namens
  Prüfschritte/de/9.1.4.5 Schriftgrafiken.adoc
Labels: changelog:changed :pencil2:, version:minor

#420 README - Ergänzung von Nutzungsbedingungen und Markenschutz
  README.md
Labels: changelog:changed :pencil2:, version:minor

#419 9.2.4.7 Aktuelle Position des Fokus deutlich - Entfernung des Bezugs auf Hervorhebung bei Mausnutzung
  Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
Labels: changelog:changed :pencil2:, version:minor
