Repository BIK-BITV/BIK-Web-Test, pull requests merged in 2025-03, with the labels that each got.

#477 9.1.1.1b Alternativtexte für Grafiken und Objekte - 80 Zeichen
  Prüfschritte/de/9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc
Labels: changelog:changed :pencil2:, version:minor

#455 9.2.4.1 Bereiche überspringbar - Hinzufügung Sprunglinks-Fokussierung…
  Prüfschritte/de/9.2.4.1 Bereiche überspringbar.adoc
Labels: changelog:added :heavy_plus_sign:, version:minor

#485 9.1.1.1d Alternativen für CAPTCHAs: Fehlendes T in CAPTCHA
  Prüfschritte/de/9.1.1.1d Alternativen für CAPTCHAs.adoc
Labels: changelog:fixed :+1:, version:patch

#486 9.1.3.1a HTML-Strukturelemente für Überschriften: FAQ ? statt .
  Prüfschritte/de/9.1.3.1a HTML-Strukturelemente für Überschriften.adoc
Labels: changelog:fixed :+1:, version:patch

#484 9.2.2.1 Zeitbegrenzungen anpassbar - Anwendbarkeit überarbeitet (Beschränkung auf Transaktionen entfernt)
  Prüfschritte/de/9.2.2.1 Zeitbegrenzungen anpassbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#483 9.2.5.7 Ziehbewegungen - Slider-Bezug beim letzen Beispiel in der Prüfschrittbeschreibung entfernt
  Prüfschritte/de/9.2.5.7 Ziehbewegungen.adoc
Labels: changelog:fixed :+1:, version:patch

#482 9.3.3.2 Beschriftungen von Formularelementen vorhanden - Beispiel Datum / Auswahllisten ausführlicher erläutert
  Prüfschritte/de/9.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc
Labels: changelog:fixed :+1:, version:patch

#481 9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar - Beispiel Datum: Ergänzung der Gruppenbeschriftung
  Prüfschritte/de/9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar.adoc
Labels: changelog:fixed :+1:, version:patch

#480 Update 9.1.4.1 Ohne Farben nutzbar - Prüfung eines Fokusindikators, der nur mithilfe von Farbänderung umgesetzt ist
  Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
Labels: changelog:changed :pencil2:, version:minor

#425 9.2.4.7 Aktuelle Position des Fokus deutlich - Verweis auf 9.1.4.1 u.a.
  Prüfschritte/de/9.2.4.7 Aktuelle Position des Fokus deutlich.adoc
Labels: changelog:changed :pencil2:, version:minor

#488 9.1.4.1 Ohne Farben nutzbar: Fehlendes Satzzeichen in FAQ
  Prüfschritte/de/9.1.4.1 Ohne Farben nutzbar.adoc
Labels: changelog:fixed :+1:, version:patch
